language: python
python:
  - '3.5'
install: pip install pip --upgrade
script: make test
notifications:
  webhooks:
    on_success: change
    on_failure: change
    on_start: false
cache:
    directories:
      - $HOME/.cache/pip
      - $HOME/local
      - $HOME/src
git:
  depth: 2147483647
before_install:
      - pip install codecov
before_script:
      - SRC_DIR=$HOME/local/src
      - NRN_INSTALL_DIR=$HOME/local/nrn
      - ./.travis_install_neuron.sh ${SRC_DIR} ${NRN_INSTALL_DIR}
      - export PATH=$PATH:${NRN_INSTALL_DIR}/x86_64/bin
      - export PYTHONPATH=$PYTHONPATH:${NRN_INSTALL_DIR}/lib/python
after_success:
      - codecov
