
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d3eb42f51df69867c0792e0c3c84103953ee873e",
 "version": "1.1.290"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
